### ISSUE TITLE
Tests broken by #206e1af

### ISSUE THREAD

**Issue by tysonmote** [szferi/gomdb#26]
Commit [#206e1af](https://github.com/szferi/gomdb/commit/206e1af66b3da9e4aa5dbe3c506df85d7bfab6fd) broke the tests:

```
# github.com/szferi/gomdb
./bench_test.go:159: not enough arguments in call to cur.Get
./bench_test.go:210: not enough arguments in call to cur.GetVal
./example_test.go:46: not enough arguments in call to cursor.Get
./mdb_test.go:85: not enough arguments in call to cursor.Get
FAIL    github.com/szferi/gomdb [build failed]
```
